### ISSUE TITLE
mount失败

### ISSUE THREAD

**Issue by andydodo** [huaweicloud/huaweicloud-obs-obsfs#1]
你好，请问obsfs支持标准s3协议吗？是不是只支持华为自己的s3服务？

1.问题:mount失败

2.描述详情: 执行 "obsfs test /mnt/test -o passwd_file=/home/dukai1/s3Pass -o url=http://10.14.28.10/ -o use_path_request_style -o dbglevel=info -f -o curldbg" mount bucket时，报错信息

Accept: */*
Authorization: AWS X0oXfMgA2Cn0plJwxy5W:QHyiy3zIrFviRKF0/Tyqn6QMxsE=
Date: Tue, 20 Aug 2019 08:44:21 GMT
x-hws-fs-client: true

< HTTP/1.1 403 Forbidden
< Content-Length: 405
< Date: Tue, 20 Aug 2019 08:44:21 GMT
< x-amz-request-id: b42a97b4-c326-11e9-8aeb-a4dcbe06256d
< Server: S3 gateway 3.0
<
* Connection #0 to host 10.174.228.130 left intact
[CRT] hws_s3fs_statis_api.cpp:s3fsStatis(150): Id[38], Step(lib_curl_send), AVG[1118 us], MAX[1118 us], total[1118 us], numSum[1]
[ERR] curl.cpp:PrintRequestId4ResponseErr(2271): curl perform failed,url=http://10.174.228.130/lvs-test/,response=403,requestid=
[INF]       curl.cpp:RequestPerform(2349): HTTP response code 403 was returned, returning EPERM. requestId:
[WAN] curl.cpp:RequestPerform(2350): Body Text: <?xml version='1.0' encoding='utf-8' ?>
<Error xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<Code>InvalidArgument</Code>
	<Message>Copy Source must mention the source bucket and key: sourcebucket/sourcekey</Message>
	<ArgumentName>Authorization header is invalid</ArgumentName>
	<RequestId>b42a97b4-c326-11e9-8aeb-a4dcbe06256d</RequestId>
	<HostId>734a89cb1fb6de381147addb6986f8b0</HostId>
</Error>

, requestId:
[ERR] curl.cpp:CheckBucket(4028): Check bucket failed, S3 response: <?xml version='1.0' encoding='utf-8' ?>
<Error xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<Code>InvalidArgument</Code>
	<Message>Copy Source must mention the source bucket and key: sourcebucket/sourcekey</Message>
	<ArgumentName>Authorization header is invalid</ArgumentName>
	<RequestId>b42a97b4-c326-11e9-8aeb-a4dcbe06256d</RequestId>
	<HostId>734a89cb1fb6de381147addb6986f8b0</HostId>
</Error>

[CRT] hws_s3fs.cpp:s3fs_check_service(2931): invalid credentials(host=http://10.174.228.130) - result of checking service.
[ERR] hws_s3fs.cpp:s3fs_exit_fuseloop(2467): Exiting FUSE event loop due to errors

[INF] hws_s3fs.cpp:s3fs_destroy(2554): destroy
[WAN] hws_s3fs.cpp:s3fs_destroy(2558): Could not release curl library.
[CRT] hws_fd_cache.cpp:setFdCacheGlobalVariableByCfg(330): gReadPageCleanMs=3000,gReadStatDiffLongMs=50000,gReadStatDiffShortMs=10000
[CRT] hws_fd_cache.cpp:setFdCacheGlobalVariableByCfg(332): gMaxCacheMemSize=1073741824,gIsCheckCRC=1
[CRT] hws_fd_cache.cpp:setFdCacheGlobalVariableByCfg(335): gReadStatSize=32,gReadStatSeqSize=24,StatSizeThreshold=4194304
[CRT] hws_fd_cache.cpp:setFdCacheGlobalVariableByCfg(339): gWritePageNum=12, gReadPageNum=12,
[CRT] hws_fd_cache.cpp:setFdCacheGlobalVariableByCfg(351): FreeCachePercent=20,g_bIntersectWriteMerge=0

**Comment by zhuxiaoran** [comment]
obsfs仅支持挂载华为云OBS并行文件系统
